-- 白日慵懶香水訂購網站：Supabase 資料庫結構
--
-- 用途：在新的 Supabase 專案從零重建資料庫（SQL Editor 整份貼上執行）。
-- 可以重複執行：已存在的資料表、欄位、擴充功能會略過，函式與排程會被覆蓋成最新版本。
-- 在後台修改資料庫之後，記得同步更新這個檔案。

-- 1. 訂單資料表 ---------------------------------------------------------------

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  order_number text not null unique,
  status text not null default 'pending',

  -- 個資：建立 30 天後由 anonymize_old_orders() 清除
  customer_name text not null,
  phone text not null,
  email text not null,
  instagram text,
  recipient_name text,
  recipient_phone text,
  pickup_store_address text not null default '',
  note text,

  -- 訂單內容與金額（金額由 Worker 依 shared/pricing.js 計算）
  small_qty integer not null default 0,
  large_qty integer not null default 0,
  pickup_method text not null,
  privacy_agreed boolean not null default false,
  subtotal integer not null,
  shipping_fee integer not null,
  total integer not null,

  -- 同一個 Turnstile token 只能建立一筆訂單（SHA-256 雜湊）
  turnstile_token_hash text unique,

  -- 個資被清除的時間；null 代表還沒清除
  anonymized_at timestamptz
);

-- 2. 權限 --------------------------------------------------------------------
-- RLS 開啟且不建立任何 policy：訪客一列都讀寫不到。
-- 前端不直接連線資料庫，所以 anon、authenticated 沒有任何權限。
-- Worker 使用 secret key（service_role），只能新增、讀取、更新，不能刪除或清空。

alter table public.orders enable row level security;

revoke all on table public.orders from anon, authenticated;

grant select, insert, update on table public.orders to service_role;
revoke delete, truncate, references, trigger on table public.orders from service_role;

-- 3. 個資保存期限：30 天後清除 --------------------------------------------------
-- 清除姓名、電話、Email、IG、地址、收件人、備註；保留編號、數量、金額與日期。
-- 修改天數時，前端隱私權同意文字（src/components/form/RecipientFields.jsx）要一起改。

create or replace function public.anonymize_old_orders()
returns integer
language sql
set search_path = ''
as $$
  with updated as (
    update public.orders
    set customer_name = '（已清除）',
        phone = '（已清除）',
        email = '（已清除）',
        instagram = '',
        pickup_store_address = '（已清除）',
        recipient_name = '（已清除）',
        recipient_phone = '（已清除）',
        note = '',
        anonymized_at = now()
    where created_at < now() - interval '30 days'
      and anonymized_at is null
    returning 1
  )
  select count(*)::integer from updated;
$$;

-- 新函式預設所有人都能執行，而且會被 Supabase 開放成 API，所以要收回。
revoke execute on function public.anonymize_old_orders() from public, anon, authenticated;

-- 4. 排程：每天台灣時間 03:00 執行（Supabase 排程使用 UTC） --------------------------

create extension if not exists pg_cron;

select cron.schedule(
  'anonymize-old-orders',
  '0 19 * * *',
  $$select public.anonymize_old_orders();$$
);

-- 執行紀錄：
-- select status, return_message, start_time
-- from cron.job_run_details
-- order by start_time desc
-- limit 5;
